# Production docker-compose
# Just like docker-compose, except it's mongo only

version: "3.8"
services:
  mongo:
    container_name: mongo
    image: mongo:4.4.1-bionic
    ports:
      - "3002:27017"
    volumes:
      - ./mongo/db:/data/db
    environment: 
      MONGO_INITDB_DATABASE: swdsdb
