# Production docker-compose

version: "3.8"
services:
  angular:
    container_name: angular
    image: nginx:1.19.2-alpine
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "express"
      - "spring"
    environment: 
      DOCKER_CONTAINER: angular
  express:
    container_name: express
    image: node:14.11.0-alpine3.12
    working_dir: "/usr/src/app"
    restart: unless-stopped
    command: "node dist"
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - "mongo"
      - "spring"
    environment: 
      DOCKER_CONTAINER: express
  mongo:
    container_name: mongo
    image: mongo:4.4.1-bionic
    restart: unless-stopped
    ports:
      - "3002:27017"
    volumes:
      - ./mongo/db:/data/db
    environment: 
      MONGO_INITDB_DATABASE: swdsdb
  spring:
    container_name: spring
    build:
      context: ./micro-services/java/ImageProcessingSpring
      dockerfile: Dockerfile
    ports:
      - "3003:8080"
  