version: "3.8"
services:
  angular:
    container_name: angular
    image: node:14.11.0-alpine3.12
    working_dir: "/usr/src/app"
    command: "npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - "express"
    environment: 
      DOCKER_CONTAINER: angular
  express:
    container_name: express
    image: node:14.11.0-alpine3.12
    working_dir: "/usr/src/app"
    command: "npm start"
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - "mongo"
    environment: 
      DOCKER_CONTAINER: express
  mongo:
    container_name: mongo
    image: mongo:4.4.1-bionic
    ports:
      - "3002:27017"
    volumes:
      - ./mongo/db:/data/db
    environment: 
      MONGO_INITDB_DATABASE: swdsdb
