name: CI

on:
  push:
    branches: [ ezzat-dev, develop, master ]
  pull_request:
    branches: [ ezzat-dev, develop, master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node modules
        run: |
          npm install
          (cd shared && npm install)
          (cd client && npm install)
          (cd server && npm install)
          (cd chrome-ext && npm install)

      - name: Run Jest Tests
        run: |
          npx jest

      - name: Check docker existence
        run: |
          docker -v
          docker-compose -v
  